version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  dep1:
      networks:
        splunknet:
          aliases:
            - dep1
      image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
      hostname: dep1
      env_file: 
        - .env
        - ../.secrets.env 
      environment:
        - SPLUNK_INDEXER_URL=idx1
        - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
        - SPLUNK_SEARCH_HEAD_URL=sh1,sh2,sh3
        - SPLUNK_DEPLOYER_URL=dep1
        - SPLUNK_CLUSTER_MASTER_URL=cm1
        - SPLUNK_ROLE=splunk_deployer
        - SPLUNK_LICENSE_URI
        - SPLUNK_DEFAULTS_URL
        - SPLUNK_APPS_URL
      ports:
        - 8100:8000
        - 8089
      volumes:
        - ./defaults:/tmp/defaults

  sh1:
    networks:
      splunknet:
        aliases:
          - sh1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh1
    container_name: sh1
    labels:
       "component" : "SHC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_DEPLOYER_URL=dep1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  sh2:
    networks:
      splunknet:
        aliases:
          - sh2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh2
    container_name: sh2
    labels:
       "component" : "SHC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_DEPLOYER_URL=dep1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  sh3:
    networks:
      splunknet:
        aliases:
          - sh3
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh3
    container_name: sh3
    labels:
       "component" : "SHC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_DEPLOYER_URL=dep1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  cm1:
    networks:
      splunknet:
        aliases:
          - cm1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: cm1
    container_name: cm1
    labels:
       "component" : "CM"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_LICENSE_URI
    ports:
      - 8300:8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx1:
    networks:
      splunknet:
        aliases:
          - idx1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx1
    container_name: idx1
    labels:
       "component" : "IDXC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx2:
    networks:
      splunknet:
        aliases:
          - idx2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx2
    container_name: idx2
    labels:
       "component" : "IDXC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  idx3:
    networks:
      splunknet:
        aliases:
          - idx3
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: idx3
    container_name: idx3
    labels:
       "component" : "IDXC"
    env_file: 
      - .env
      - ../.secrets.env 
    environment:
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults:/tmp/defaults

  adminsh:
    networks:
      splunknet:
        aliases:
          - adminsh
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: adminsh
    container_name: adminsh
    labels:
       "component" : "SH"
    env_file: 
      - .env
      - ../.secrets.env
    environment:
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_CLUSTER_MASTER_URL=cm1
      - SPLUNK_ROLE=splunk_monitor
      - SPLUNK_LICENSE_URI
    ports:
      - 8000:8000
      - 8089:8089
    volumes:
      - ./defaults:/tmp/defaults

  lm:
    networks:
      splunknet:
        aliases:
          - lm
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: lm
    container_name: lm
    labels:
       "component" : "LM"
    env_file: 
      - .env   
      - ../.secrets.env 
    environment:
      - SPLUNK_LICENSE_MASTER_URL=lm
      - SPLUNK_ROLE=splunk_license_master
      - SPLUNK_LICENSE_URI=/tmp/splunk.lic
    volumes:
      - ./defaults:/tmp/defaults
      - ./splunk.lic:/tmp/splunk.lic      